[[edge_functions]]
  path = "/api/ai/sessions/*"
  function = "get-ai-sessions"

[build]
  base = "web"
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200
  force = true