version: '3.1'

services:

  node:
    image: node:14
    working_dir: /home/node/app
    command: yarn dev
    volumes:
      - ../:/home/node/app
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongolara
      MONGODB_COLLECTION: results
      BASE_URL: http://localhost:3000
